imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: ca

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']
    globals:
        google_analytics_enabled: %google_analytics_enabled%
        google_analytics_account: "%google_analytics_account%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    java:           "%assetic_path_java%"
    node:           "%assetic_path_node%"
    filters:
        cssrewrite: ~
        less:
            node:       "%assetic_path_node%"
            node_paths: [ "%assetic_path_node_modules%" ]
    assets:
        mycss:
            inputs:
                - "@AppBundle/Resources/public/css/main.less"
                - "@AppBundle/Resources/public/css/icomoon.less"
        myjs:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%database_path%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: ssl
    auth_mode:  login
    spool:     { type: memory }

cypress_git_elephant:
    enable_profiler: false
