security:
    providers:
        in_memory:
            memory:
                users:
                    %admin_user%:
                        password: "%admin_password%"
                        roles:
                            - 'ROLE_ADMIN'
                            - 'ROLE_SONATA_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: ~
            http_basic: ~
        main:
            anonymous: ~

    access_control:
        # require ROLE_ADMIN for all /admin/... routes
        - { path: ^/admin, roles: ROLE_ADMIN }
