services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    app.mailer:
        class: AppBundle\Service\MailerService
        arguments: [@swiftmailer.mailer.default]
