services:
# App
    app.google_maps_service:
        class: AppBundle\Service\GoogleMapsService
# Sonata Admins
    admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [ ~, AppBundle\Entity\Contact, AppBundle\Controller\Admin\ContactAdminController, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Missatges de contacte", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [ ~, AppBundle\Entity\Category, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categories", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [ ~, AppBundle\Entity\Post, AppBundle\Controller\Admin\PostAdminController, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Articles", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.customer:
        class: AppBundle\Admin\Old\CustomerAdmin
        arguments: [ ~, AppBundle\Entity\Old\Customer, AppBundle\Controller\Admin\Old\CustomerAdminController, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Alumnes", group: "Facturació", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.schedule:
        class: AppBundle\Admin\Old\ScheduleAdmin
        arguments: [ ~, AppBundle\Entity\Old\Schedule, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Partes", group: "Facturació", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.phone:
        class: AppBundle\Admin\Old\PhoneAdmin
        arguments: [ ~, AppBundle\Entity\Old\Phone, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Telèfons", group: "Facturació", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.hoursingle:
        class: AppBundle\Admin\Old\HourSingleAdmin
        arguments: [ ~, AppBundle\Entity\Old\HourSingle, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Hora Particular", group: "Facturació", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.monthgroup:
        class: AppBundle\Admin\Old\MonthGroupAdmin
        arguments: [ ~, AppBundle\Entity\Old\MonthGroup, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Mes en grup", group: "Facturació", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.receipt:
        class: AppBundle\Admin\Old\ReceiptAdmin
        arguments: [ ~, AppBundle\Entity\Old\Receipt, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Rebut", group: "Facturació", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.spending:
        class: AppBundle\Admin\Old\SpendingAdmin
        arguments: [ ~, AppBundle\Entity\Old\Spending, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Despesa", group: "Despesa", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.spendingcategory:
        class: AppBundle\Admin\Old\SpendingCategoryAdmin
        arguments: [ ~, AppBundle\Entity\Old\SpendingCategory, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categoria", group: "Despesa", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuaris", group: "Administrador", label_translator_strategy: "sonata.admin.label.strategy.noop" }
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments: [ "@swiftmailer.mailer" ]
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments: [ "@app.courier", "@twig", "%mailer_destination%", "%mailer_url_base%" ]
# Sonata Blocks
    admin.block.messages:
        class: AppBundle\Admin\Block\PendingMessagesBlock
        tags:
            - { name: sonata.block }
        arguments: [ "sonata.admin.block.messages", "@templating", "@doctrine.orm.entity_manager" ]
    admin.block.graphs:
        class: AppBundle\Admin\Block\GraphsBlock
        tags:
            - { name: sonata.block }
        arguments: [ "sonata.admin.block.graphs", "@templating", "@doctrine.orm.entity_manager" ]
# Sitemap
    app.sitemap:
        class: AppBundle\Listener\SitemapListener
        arguments: [ "@router", "@doctrine.orm.entity_manager" ]
        tags: [ { name: "presta.sitemap.listener" } ]
# Twig
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
